# docker-compose.yml

services:
  db:
    image: postgres:15
    container_name: oxsbank_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Oxossi96
      POSTGRES_DB: oxsbankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: OxsBank.API/Dockerfile
    container_name: oxsbank_api
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=oxsbankdb;Username=postgres;Password=Oxossi96"
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - .:/app
    command: ["dotnet", "OxsBank.API.dll"]

volumes:
  postgres_data:

# Estrutura de diretórios:
# - OxsBank
#   - src
#     - OxsBank.API (Apresentação)
#     - OxsBank.Application (Regras de Negócio)
#     - OxsBank.Domain (Entidades e Interfaces)
#     - OxsBank.Infrastructure (Acesso a Dados e Serviços Externos)